// Expense List Request
export const REQUEST_EXPENSE_LIST = "REQUEST_EXPENSE_LIST";
export const RECEIVE_EXPENSE_LIST = "RECEIVE_EXPENSE_LIST";

// Add Expense Request
export const REQUEST_ADD_EXPENSE = "REQUEST_ADD_EXPENSE";
export const RECEIVE_ADD_EXPENSE = "RECEIVE_ADD_EXPENSE";

// Edit to Expense
export const REQUEST_EDIT_EXPENSE = "REQUEST_EDIT_EXPENSE";
export const RECEIVE_EDIT_EXPENSE = "RECEIVE_EDIT_EXPENSE";

// REMOVE Expense
export const REQUEST_REMOVE_EXPENSE = "REQUEST_REMOVE_EXPENSE"
export const RECEIVE_REMOVE_EXPENSE = "RECEIVE_REMOVE_EXPENSE"
